### PR TITLE
Add Toggle Node IDs Text

### PR DESCRIPTION
**Pull request by Blenux**
- Added ability to toggle the Node IDs text off and on.

### CODE REVIEW

**Comment by angelo234** [comment]
Btw, the changes looked good and everything worked properly for me. Although I just moved the "Toggle NodeIDs Text" property to be part of the UIProperties class rather than being directly part of the scene.

**Comment by angelo234** [comment]
Let me know if you like my changes or not and I'll merge the changes :)

**Comment by Blenux** [comment]
Oh yeah that's fine, I did have it similar to that way at first, but loading a saved .blend file the toggle wouldn't work unless the addon was reloaded again, probably something I was doing wrong.

**Comment by angelo234** [comment]
Hmm interesting. I tried saving it and loading it back in and seems to be working. I'll merge the changes then.

**Pull request merged**
